 #events but only for the master branch
on:
  push:
    branches: [main]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Installing Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 12

      # Runs a set of commands using the runners shell
      - name: Installing surge
        run: npm install --global surge
      - name: deploying using surge
        run: surge ./ bootcamp2020_sample1.surge.sh --token ${{ secrets.SURGE_TOKEN }}
